--
-- Equivalent PostgreSQL de aurox_tests.sql (base de test de la lib).
-- Charger avec : psql -U <user> -d aurox_tests -f aurox_tests_pgsql.sql
--
-- Correspondances avec le dump MySQL :
--   int unsigned AUTO_INCREMENT           -> integer GENERATED BY DEFAULT AS IDENTITY
--   enum('draft','published','archived')  -> varchar + CHECK
--   datetime ON UPDATE CURRENT_TIMESTAMP  -> trigger (pas d'equivalent natif en pg)
--   utf8mb4                               -> encodage UTF8 de la base
--

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar(255) NOT NULL,
    content       text,
    short         text,
    img_src       varchar(255) DEFAULT NULL,
    img_alt       varchar(255) DEFAULT NULL,
    link_facebook varchar(255) DEFAULT NULL,
    link_linkedin varchar(255) DEFAULT NULL,
    author_id     integer DEFAULT NULL,
    category_id   integer DEFAULT NULL,
    created_at    timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamptz DEFAULT CURRENT_TIMESTAMP,
    published_at  timestamptz DEFAULT NULL,
    status        varchar(16) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    slug          varchar(255) DEFAULT NULL,
    meta_title    varchar(255) DEFAULT NULL,
    meta_desc     varchar(255) DEFAULT NULL
);

-- Remplace le ON UPDATE CURRENT_TIMESTAMP de MySQL
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER posts_set_updated_at
    BEFORE UPDATE ON posts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO posts (id, title, content, short, img_src, img_alt, link_facebook, link_linkedin, author_id, category_id, created_at, updated_at, published_at, status, slug, meta_title, meta_desc) VALUES
    (1, 'title1', 'content1', 'short1', 'img_src', 'imalt1', 'link_fb1', 'link_lkd1', 1, NULL, '2025-04-18 20:14:49', '2025-04-18 20:14:49', NULL, 'draft', NULL, NULL, NULL),
    (2, 'title2', 'content2', 'short2', 'img_src', 'imalt2', 'link_fb2', 'link_lkd2', 2, 1,    '2025-04-18 20:14:49', '2025-04-18 20:14:49', NULL, 'draft', NULL, NULL, NULL);

-- L'identity ne connait pas les ids inseres explicitement, on la recale
SELECT setval(pg_get_serial_sequence('posts', 'id'), (SELECT MAX(id) FROM posts));
